FROM ubuntu:latest

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git cmake python3 python3-pip

COPY ./requirements.txt .

RUN python3 -m pip install --upgrade pip && \
    pip install -r requirements.txt
